### ISSUE TITLE
Agent start problem

### ISSUE THREAD

**Issue by speres** [informix/informixhq-agent#3]
When I start the agent it keep trying to start giving the message:
INFO com.informix.hq.agent.WebSocketManager - Attempting to connect to server at ws://srvinfx12:1526/ws/

**Comment by speres** [comment]
Hi Cristian,

But I have the server working, alias the server is running over the same machine.
My agent.properties is this:

id=0
target.url=jdbc:informix-sqli://srvinfx12:1526/sysmaster:informixserver=srvinfx12_net;user=informix;password=airc00
repository.url=jdbc:informix-sqli://srvinfx12:1526/monitor_db:informixserver=srvinfx12_net;user=informix;password=airc00
server.host=srvinfx12
server.port=1526


Thanks for your reply,

SP


Sérgio Peres
Administração de Sistemas

AIRC - Associação de Informática da Região Centro
Coimbra iParque, Lote nº 15,
3040-540 Antanhol – Coimbra
Portugal
+351-239850536                  | Directo
+351-919324330                  | Movel
sergio.peres@airc.pt<mailto:sergio.peres@airc.pt>           | e-Mail
www.airc.pt<http://www.airc.pt/>                           | website

De: Cristian Traistaru <notifications@github.com>
Enviada: 7 de maio de 2018 15:22
Para: informix/informixhq-agent <informixhq-agent@noreply.github.com>
Cc: Sergio Peres <sergio.peres@airc.pt>; Author <author@noreply.github.com>
Assunto: Re: [informix/informixhq-agent] Agent start problem (#3)


In the agent properties file, server.host and server.port refer to InformixHQ server, not the database. You cannot currently run the agent without it connecting to the InformixHQ server.

**Comment by cristian-t** [comment]
Once again, `server.host` and `server.port` are incorrect. You need to have a running InformixHQ server (https://github.com/informix/informixhq-server), and set `server.host` and `server.port` to point to it.

**Comment by speres** [comment]
Problem solved, thanks for your reply|

Sérgio Peres
Administração de Sistemas

AIRC - Associação de Informática da Região Centro
Coimbra iParque, Lote nº 15,
3040-540 Antanhol – Coimbra
Portugal
+351-239850536                  | Directo
+351-919324330                  | Movel
sergio.peres@airc.pt<mailto:sergio.peres@airc.pt>           | e-Mail
www.airc.pt<http://www.airc.pt/>                           | website

De: Cristian Traistaru <notifications@github.com>
Enviada: 7 de maio de 2018 16:53
Para: informix/informixhq-agent <informixhq-agent@noreply.github.com>
Cc: Sergio Peres <sergio.peres@airc.pt>; Author <author@noreply.github.com>
Assunto: Re: [informix/informixhq-agent] Agent start problem (#3)


Once again, server.host and server.port are incorrect. You need to have a running InformixHQ server (https://github.com/informix/informixhq-server), and set server.host and server.port to point to it.
